### ISSUE TITLE
Docs: error in mesh_headlight.py example

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari-threedee/napari-threedee#103]
Two of the example scripts produce an error when I try to run them:
- `examples/plugin/mesh_headlight.py`, and
- `examples/library/mesh_headlight.py` (effectively they are the same example script)

It's having a problem loading in the surface data from nilearn.

Traceback:
```
python mesh_headlight.py
Traceback (most recent call last):
  File "/Users/genevieb/Documents/GitHub/napari-threedee/docs/examples/plugin/mesh_headlight.py", line 26, in <module>
    brain_vertices, brain_faces = surface.load_surf_data(fsaverage['pial_left'])
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/nilearn/surface/surface.py", line 733, in load_surf_data
    data_part = _gifti_img_to_data(gii)
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/nilearn/surface/surface.py", line 684, in _gifti_img_to_data
    return np.asarray([arr.data for arr in gifti_img.darrays]).T.squeeze()
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
```

I have nilearn version '0.10.0'. Perhaps it would work better with an older version?

Here's the rest of my conda environment
<details>
<summary>conda list:</summary>

```
# Name                    Version                   Build  Channel
aiobotocore               2.4.2                    pypi_0    pypi
aiohttp                   3.8.3                    pypi_0    pypi
aioitertools              0.11.0                   pypi_0    pypi
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
alabaster                 0.7.13                   pypi_0    pypi
anyio                     3.6.2              pyhd8ed1ab_0    conda-forge
aom                       3.5.0                h7ea286d_0    conda-forge
app-model                 0.1.1                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py310h8e9501a_3    conda-forge
arrow                     1.2.3                    pypi_0    pypi
asciitree                 0.3.3                    pypi_0    pypi
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
attrs                     22.2.0             pyh71513ae_0    conda-forge
awkward                   2.0.8                    pypi_0    pypi
awkward-cpp               9                        pypi_0    pypi
babel                     2.12.1             pyhd8ed1ab_1    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.0             pyha770c72_0    conda-forge
binaryornot               0.4.4                    pypi_0    pypi
black                     22.12.0                  pypi_0    pypi
bleach                    6.0.0              pyhd8ed1ab_0    conda-forge
botocore                  1.27.59                  pypi_0    pypi
brotli                    1.0.9                    pypi_0    pypi
brotlipy                  0.7.0           py310h8e9501a_1005    conda-forge
build                     0.10.0                   pypi_0    pypi
bzip2                     1.0.8                h3422bc3_4    conda-forge
c-ares                    1.18.1               h3422bc3_0    conda-forge
ca-certificates           2022.12.7            h4653dfc_0    conda-forge
cachey                    0.2.1                    pypi_0    pypi
callouts                  0.1.1                    pypi_0    pypi
certifi                   2022.12.7                pypi_0    pypi
cffi                      1.15.1          py310h2399d43_3    conda-forge
cfgv                      3.3.1                    pypi_0    pypi
chardet                   5.1.0                    pypi_0    pypi
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
check-manifest            0.49                     pypi_0    pypi
click                     8.1.3           unix_pyhd8ed1ab_2    conda-forge
cloudpickle               2.2.0                    pypi_0    pypi
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.1.3              pyhd8ed1ab_0    conda-forge
commonmark                0.9.1                    pypi_0    pypi
contourpy                 1.0.7                    pypi_0    pypi
cookiecutter              2.1.1                    pypi_0    pypi
coverage                  7.0.5                    pypi_0    pypi
cryptography              39.0.2          py310hfc83b78_0    conda-forge
csscompressor             0.9.5                    pypi_0    pypi
cssselect2                0.7.0                    pypi_0    pypi
curl                      7.88.1               h9049daf_1    conda-forge
cycler                    0.11.0                   pypi_0    pypi
dask                      2023.1.0                 pypi_0    pypi
debugpy                   1.6.6           py310h0f1eb42_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
distlib                   0.3.6              pyhd8ed1ab_0    conda-forge
docstring-parser          0.15                     pypi_0    pypi
docutils                  0.17.1                   pypi_0    pypi
double-conversion         3.2.0                hb7217d7_1    conda-forge
eigen                     3.4.0                hc021e02_0    conda-forge
einops                    0.6.0                    pypi_0    pypi
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
exceptiongroup            1.1.0                    pypi_0    pypi
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                hb7217d7_0    conda-forge
fasteners                 0.18                     pypi_0    pypi
ffmpeg                    5.1.2           gpl_hf318d42_106    conda-forge
filelock                  3.10.3             pyhd8ed1ab_0    conda-forge
flake8                    6.0.0                    pypi_0    pypi
flit-core                 3.8.0              pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h82840c6_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.12.1               hd633e50_1    conda-forge
freetype-py               2.3.0                    pypi_0    pypi
frozenlist                1.3.3           py310h8e9501a_0    conda-forge
fsspec                    2022.11.0                pypi_0    pypi
gettext                   0.21.1               h0186832_0    conda-forge
ghp-import                2.1.0              pyhd8ed1ab_0    conda-forge
gitdb                     4.0.10                   pypi_0    pypi
gitpython                 3.1.31                   pypi_0    pypi
gl2ps                     1.4.2                h17b34a0_0    conda-forge
glew                      2.1.0                h9f76cd9_2    conda-forge
glib                      2.74.1               hb5ab8b9_1    conda-forge
glib-tools                2.74.1               hb5ab8b9_1    conda-forge
gmp                       6.2.1                h9f76cd9_0    conda-forge
gnutls                    3.7.8                h9f1a10d_0    conda-forge
griffe                    0.25.5                   pypi_0    pypi
gst-plugins-base          1.22.0               h8b7775e_2    conda-forge
gstreamer                 1.22.0               hcb7b3dd_2    conda-forge
hdf4                      4.2.15               h1a38d6a_5    conda-forge
hdf5                      1.12.2          nompi_ha7af310_101    conda-forge
heapdict                  1.0.1                    pypi_0    pypi
hsluv                     5.0.3                    pypi_0    pypi
html5lib                  1.1                      pypi_0    pypi
htmlmin2                  0.1.13                   pypi_0    pypi
hypothesis                6.62.1                   pypi_0    pypi
icu                       70.1                 h6b3803e_0    conda-forge
identify                  2.5.13                   pypi_0    pypi
idna                      3.4                pyhd8ed1ab_0    conda-forge
imageio                   2.24.0                   pypi_0    pypi
imageio-ffmpeg            0.4.8                    pypi_0    pypi
imagesize                 1.4.1                    pypi_0    pypi
importlib-metadata        6.1.0              pyha770c72_0    conda-forge
importlib_metadata        6.1.0                hd8ed1ab_0    conda-forge
importlib_resources       5.12.0             pyhd8ed1ab_0    conda-forge
in-n-out                  0.1.6                    pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
ipykernel                 6.22.0             pyh736e0ef_0    conda-forge
ipython                   8.11.0             pyhd1c38e8_0    conda-forge
ipython-genutils          0.2.0                    pypi_0    pypi
ipython_genutils          0.2.0                      py_1    conda-forge
isort                     5.11.4                   pypi_0    pypi
jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
jinja2                    3.0.3                    pypi_0    pypi
jinja2-time               0.2.0                    pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h1a8c8d9_3    conda-forge
jsmin                     3.0.1                    pypi_0    pypi
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsoncpp                   1.9.5                hc021e02_1    conda-forge
jsonschema                4.17.3             pyhd8ed1ab_0    conda-forge
jupyter-cache             0.5.0                    pypi_0    pypi
jupyter_client            8.1.0              pyhd8ed1ab_0    conda-forge
jupyter_core              5.3.0           py310hbe9552e_0    conda-forge
jupyter_events            0.6.3              pyhd8ed1ab_0    conda-forge
jupyter_server            2.3.0              pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    conda-forge
jupyterlab                3.5.2              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.19.0             pyhd8ed1ab_0    conda-forge
kiwisolver                1.4.4                    pypi_0    pypi
krb5                      1.20.1               h69eda48_0    conda-forge
lame                      3.100             h1a8c8d9_1003    conda-forge
lerc                      4.0.0                h9a09cb3_0    conda-forge
libaec                    1.0.6                hb7217d7_1    conda-forge
libblas                   3.9.0           16_osxarm64_openblas    conda-forge
libcblas                  3.9.0           16_osxarm64_openblas    conda-forge
libclang                  14.0.6          default_h81a5282_0    conda-forge
libclang13                14.0.6          default_he70ec0d_0    conda-forge
libcurl                   7.88.1               h9049daf_1    conda-forge
libcxx                    15.0.7               h75e25f2_0    conda-forge
libdeflate                1.17                 h1a8c8d9_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           12_2_0_hd922786_31    conda-forge
libgfortran5              12.2.0              h0eea778_31    conda-forge
libglib                   2.74.1               h4646484_1    conda-forge
libiconv                  1.17                 he4db4b2_0    conda-forge
libidn2                   2.3.4                h1a8c8d9_0    conda-forge
liblapack                 3.9.0           16_osxarm64_openblas    conda-forge
libllvm14                 14.0.6               hf6e71e7_1    conda-forge
libnetcdf                 4.9.1           nompi_h232cb48_101    conda-forge
libnghttp2                1.52.0               hae82a92_0    conda-forge
libogg                    1.3.4                h27ca646_1    conda-forge
libopenblas               0.3.21          openmp_hc731615_3    conda-forge
libopus                   1.3.1                h27ca646_1    conda-forge
libpng                    1.6.39               h76d750c_0    conda-forge
libpq                     15.2                 h1a28acd_0    conda-forge
libsodium                 1.0.18               h27ca646_1    conda-forge
libsqlite                 3.40.0               h76d750c_0    conda-forge
libssh2                   1.10.0               h7a5bd25_3    conda-forge
libtasn1                  4.19.0               h1a8c8d9_0    conda-forge
libtheora                 1.1.1             h3422bc3_1005    conda-forge
libtiff                   4.5.0                h5dffbdd_2    conda-forge
libunistring              0.9.10               h3422bc3_0    conda-forge
libvorbis                 1.3.7                h9f76cd9_0    conda-forge
libvpx                    1.11.0               hc470f4d_3    conda-forge
libwebp-base              1.3.0                h1a8c8d9_0    conda-forge
libxml2                   2.10.3               h67585b2_4    conda-forge
libxslt                   1.1.37               h1bd8bc4_0    conda-forge
libzip                    1.9.2                h76ab92c_1    conda-forge
libzlib                   1.2.13               h03a7124_4    conda-forge
livereload                2.6.3                    pypi_0    pypi
llvm-openmp               16.0.0               h7cfbb63_0    conda-forge
locket                    1.0.0                    pypi_0    pypi
loguru                    0.6.0           py310hbe9552e_2    conda-forge
lxml                      4.9.2           py310h85b680a_0    conda-forge
lz4-c                     1.9.4                hb7217d7_0    conda-forge
magicgui                  0.6.1                    pypi_0    pypi
markdown                  3.3.7              pyhd8ed1ab_0    conda-forge
markdown-callouts         0.3.0                    pypi_0    pypi
markdown-it-py            2.2.0              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.2           py310h8e9501a_0    conda-forge
matplotlib                3.6.3                    pypi_0    pypi
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mccabe                    0.7.0                    pypi_0    pypi
mdit-py-plugins           0.3.5                    pypi_0    pypi
mdurl                     0.1.0              pyhd8ed1ab_0    conda-forge
mdx-gh-links              0.3                      pypi_0    pypi
mergedeep                 1.3.4              pyhd8ed1ab_0    conda-forge
meshio                    5.0.0                    pypi_0    pypi
mistune                   2.0.5              pyhd8ed1ab_0    conda-forge
mkdocs                    1.2.4                    pypi_0    pypi
mkdocs-autorefs           0.4.1                    pypi_0    pypi
mkdocs-callouts           1.9.0                    pypi_0    pypi
mkdocs-click              0.8.0                    pypi_0    pypi
mkdocs-gallery            0.7.6                    pypi_0    pypi
mkdocs-git-revision-date-localized-plugin 1.2.0                    pypi_0    pypi
mkdocs-literate-nav       0.6.0                    pypi_0    pypi
mkdocs-material           8.2.7                    pypi_0    pypi
mkdocs-material-extensions 1.1.1              pyhd8ed1ab_0    conda-forge
mkdocs-minify-plugin      0.6.4                    pypi_0    pypi
mkdocs-pdf-export-plugin  0.5.10                   pypi_0    pypi
mkdocs-redirects          1.2.0                    pypi_0    pypi
mkdocs-video              1.4.0                    pypi_0    pypi
mkdocstrings              0.20.0                   pypi_0    pypi
mkdocstrings-python       0.8.3                    pypi_0    pypi
mkpdfs-mkdocs             1.0.1                    pypi_0    pypi
morphosamplers            0.0.5                    pypi_0    pypi
multidict                 6.0.4           py310h8e9501a_0    conda-forge
mypy-extensions           0.4.3                    pypi_0    pypi
mysql-common              8.0.32               h518ea0a_1    conda-forge
mysql-libs                8.0.32               hcb599eb_1    conda-forge
myst-nb                   0.17.1                   pypi_0    pypi
myst-parser               0.18.1                   pypi_0    pypi
napari                    0.5.0a2.dev53+g23323b21          pypi_0    pypi
napari-animation          0.0.6.dev0+gd8bd609.d20230120          pypi_0    pypi
napari-bio-sample-data    0.0.4                    pypi_0    pypi
napari-console            0.0.7                    pypi_0    pypi
napari-meshio             0.1.dev15+g3d7d904.d20230306          pypi_0    pypi
napari-plugin-engine      0.2.0                    pypi_0    pypi
napari-sphinx-theme       0.2.1                    pypi_0    pypi
napari-svg                0.1.6                    pypi_0    pypi
napari-threedee           0.0.4.dev2+gb83d6c6           dev_0    <develop>
nbclassic                 0.5.2              pyhd8ed1ab_0    conda-forge
nbclient                  0.5.13                   pypi_0    pypi
nbconvert                 7.2.9              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.2.9              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          7.2.9              pyhd8ed1ab_0    conda-forge
nbformat                  5.8.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h07bb92c_1    conda-forge
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
nettle                    3.8.1                h63371fa_1    conda-forge
networkx                  3.0                      pypi_0    pypi
nibabel                   5.0.1              pyhd8ed1ab_0    conda-forge
nilearn                   0.10.0             pyhd8ed1ab_0    conda-forge
nlohmann_json             3.11.2               h2e04ded_0    conda-forge
nodeenv                   1.7.0                    pypi_0    pypi
notebook                  6.5.2              pyha770c72_1    conda-forge
notebook-shim             0.2.2              pyhd8ed1ab_0    conda-forge
npe2                      0.6.2                    pypi_0    pypi
nspr                      4.35                 hb7217d7_0    conda-forge
nss                       3.89                 h789eff7_0    conda-forge
numcodecs                 0.11.0                   pypi_0    pypi
numpy                     1.24.1                   pypi_0    pypi
numpydoc                  1.5.0                    pypi_0    pypi
openh264                  2.3.1                hb7217d7_2    conda-forge
openssl                   3.1.0                h03a7124_0    conda-forge
p11-kit                   0.24.1               h29577a5_0    conda-forge
packaging                 23.0               pyhd8ed1ab_0    conda-forge
pandas                    1.5.2                    pypi_0    pypi
pandoc                    2.19.2               hce30654_2    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.3.0                    pypi_0    pypi
pathspec                  0.10.3                   pypi_0    pypi
pcre2                     10.40                hb34f9b4_0    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.4.0                    pypi_0    pypi
pint                      0.20.1                   pypi_0    pypi
pip                       22.3.1             pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
platformdirs              3.1.1              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0              pyhd8ed1ab_5    conda-forge
ply                       3.11                       py_1    conda-forge
pooch                     1.6.0                    pypi_0    pypi
pre-commit                2.21.0                   pypi_0    pypi
proj                      9.1.1                h13f728c_2    conda-forge
prometheus_client         0.16.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.38             pyha770c72_0    conda-forge
prompt_toolkit            3.0.38               hd8ed1ab_0    conda-forge
psutil                    5.9.4           py310h8e9501a_0    conda-forge
psygnal                   0.7.0                    pypi_0    pypi
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pugixml                   1.11.4               hbdafb3b_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
py                        1.11.0             pyh6c4a22f_0    conda-forge
pycodestyle               2.10.0                   pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydantic                  1.10.4                   pypi_0    pypi
pydyf                     0.5.0                    pypi_0    pypi
pyflakes                  3.0.1                    pypi_0    pypi
pygments                  2.14.0             pyhd8ed1ab_0    conda-forge
pymdown-extensions        9.10               pyhd8ed1ab_0    conda-forge
pyopengl                  3.1.6                    pypi_0    pypi
pyopenssl                 23.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9                    pypi_0    pypi
pyphen                    0.13.2                   pypi_0    pypi
pyproject-hooks           1.0.0                    pypi_0    pypi
pyqt                      5.15.7          py310h7aaa74b_2    conda-forge
pyqt5-sip                 12.11.0         py310h0f1eb42_2    conda-forge
pyqtgraph                 0.13.2             pyhd8ed1ab_0    conda-forge
pyrsistent                0.19.3          py310h8e9501a_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytest                    7.2.1                    pypi_0    pypi
pytest-cov                4.0.0                    pypi_0    pypi
pytest-qt                 4.2.0                    pypi_0    pypi
python                    3.10.8          h3ba56d0_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-dotenv             0.21.0                   pypi_0    pypi
python-fastjsonschema     2.16.3             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python-slugify            7.0.0                    pypi_0    pypi
python_abi                3.10                    3_cp310    conda-forge
pytomlpp                  1.0.11                   pypi_0    pypi
pytz                      2022.7.1           pyhd8ed1ab_0    conda-forge
pyvirtualdisplay          3.0                      pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0             py310h8e9501a_5    conda-forge
pyyaml-env-tag            0.1                pyhd8ed1ab_0    conda-forge
pyzmq                     25.0.2          py310hc407298_0    conda-forge
qt-main                   5.15.8               hfe8d25c_6    conda-forge
qtconsole                 5.4.0                    pypi_0    pypi
qtgallery                 0.0.2                    pypi_0    pypi
qtpy                      2.3.0                    pypi_0    pypi
readline                  8.2                  h92ec313_1    conda-forge
regex                     2022.10.31      py310h8e9501a_0    conda-forge
requests                  2.28.2             pyhd8ed1ab_0    conda-forge
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
rich                      13.3.2             pyhd8ed1ab_0    conda-forge
s3fs                      2022.11.0                pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scikit-learn              1.2.2           py310ha00a7cd_0    conda-forge
scipy                     1.10.0                   pypi_0    pypi
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                67.6.0             pyhd8ed1ab_0    conda-forge
sip                       6.7.7           py310h0f1eb42_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smmap                     5.0.0                    pypi_0    pypi
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
snowballstemmer           2.2.0                    pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sphinx                    4.5.0                    pypi_0    pypi
sphinx-autobuild          2021.3.14                pypi_0    pypi
sphinx-autodoc-typehints  1.12.0                   pypi_0    pypi
sphinx-copybutton         0.5.1                    pypi_0    pypi
sphinx-design             0.3.0                    pypi_0    pypi
sphinx-external-toc       0.3.1                    pypi_0    pypi
sphinx-favicon            1.0.1                    pypi_0    pypi
sphinx-gallery            0.12.2                   pypi_0    pypi
sphinx-rtd-theme          1.2.0                    pypi_0    pypi
sphinx-tabs               3.4.0                    pypi_0    pypi
sphinx-tags               0.2.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.3                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jquery      4.1                      pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlalchemy                1.4.46                   pypi_0    pypi
sqlite                    3.40.0               h2229b38_0    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
superqt                   0.4.1                    pypi_0    pypi
svt-av1                   1.4.1                h7ea286d_0    conda-forge
tabulate                  0.9.0                    pypi_0    pypi
tbb                       2021.8.0             hffc8910_0    conda-forge
tbb-devel                 2021.8.0             h4f9cb39_0    conda-forge
tensorstore               0.1.30                   pypi_0    pypi
terminado                 0.17.1             pyhd1c38e8_0    conda-forge
text-unidecode            1.3                      pypi_0    pypi
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tifffile                  2022.10.10               pypi_0    pypi
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.12.0                   pypi_0    pypi
torch                     1.13.1                   pypi_0    pypi
tornado                   6.2             py310h8e9501a_1    conda-forge
tox                       3.27.1             pyhd8ed1ab_0    conda-forge
tqdm                      4.64.1                   pypi_0    pypi
traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
typer                     0.7.0                    pypi_0    pypi
typing-extensions         4.5.0                hd8ed1ab_0    conda-forge
typing_extensions         4.5.0              pyha770c72_0    conda-forge
tzdata                    2022g                h191b570_0    conda-forge
urllib3                   1.26.15            pyhd8ed1ab_0    conda-forge
utfcpp                    3.2.3                hce30654_0    conda-forge
v                         3.4.0                    pypi_0    pypi
virtualenv                20.17.1                  pypi_0    pypi
vispy                     0.12.1                   pypi_0    pypi
vtk                       9.2.6           qt_py310h87518ef_200    conda-forge
watchdog                  2.3.1           py310h8e9501a_0    conda-forge
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
weasyprint                58.1                     pypi_0    pypi
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.5.1              pyhd8ed1ab_0    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
wrapt                     1.14.1                   pypi_0    pypi
wslink                    1.10.1             pyhd8ed1ab_0    conda-forge
x264                      1!164.3095           h57fd34a_2    conda-forge
x265                      3.5                  hbc6ce65_3    conda-forge
xarray                    2022.12.0                pypi_0    pypi
xz                        5.2.6                h57fd34a_0    conda-forge
yaml                      0.2.5                h3422bc3_2    conda-forge
yarl                      1.8.2           py310h8e9501a_0    conda-forge
zarpaint                  0.2.0                    pypi_0    pypi
zarr                      2.13.3                   pypi_0    pypi
zeromq                    4.3.4                hbdafb3b_1    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h03a7124_4    conda-forge
zopfli                    0.2.2                    pypi_0    pypi
zstd                      1.5.2                hf913c23_6    conda-forge
```

</details>

**Comment by kevinyamauchi** [comment]
Ah thanks for the heads up. I'm doing some work on the headlight right now and I can look into it.

**Comment by kevinyamauchi** [comment]
It looks like the issue is that `nilearn`is instantiating the arrays in a way that was deprecated by numpy. I previously had numpy `1.23.3` and it worked, but emitted a deprecation warning. I updated to numpy `1.24.2` and it now fails with the error you reported. I don't think we should constrain the numpy version for an example mesh, so I will look elsewhere for an example mesh. Thanks for reporting this!
